version: '3.8'

services:
  # Dịch vụ ứng dụng JCertPre-BE
  jcertpre-be:
    image: wakiwaki2922/jcertpre-be:latest
    container_name: jcertpre-be-container
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      # Đọc các biến môi trường từ file .env cùng cấp
      - .env

  # Dịch vụ Watchtower để tự động cập nhật image
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 jcertpre-be-container

networks:
  default:
    driver: bridge
