services:
  jcertpre-be:
    image: wakiwaki2922/jcertpre-be:latest
    container_name: jcertpre-be-container
    restart: unless-stopped
    ports:
      - "5001:8080"
    env_file:
      - .env

networks:
  default:
    driver: bridge
