version: '3.8'

services:
  jcertpre-be:
    image: wakiwaki2922/jcertpre-be:v1.0
    container_name: jcertpre-be-container
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env

networks:
  default:
    driver: bridge
