// <auto-generated />
using System;
using JCertPreApplication.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JCertPreApplication.Persistence.Migrations
{
    [DbContext(typeof(JCertPreDatabaseContext))]
    [Migration("20250726034754_ChangeTotalScoreToInt")]
    partial class ChangeTotalScoreToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.Property<Guid>("ConversationsconversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantsuserId")
                        .HasColumnType("uuid");

                    b.HasKey("ConversationsconversationId", "ParticipantsuserId");

                    b.HasIndex("ParticipantsuserId");

                    b.ToTable("conversation_participant", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("answerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("attemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("choiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uuid");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.HasKey("answerId");

                    b.HasIndex("attemptId");

                    b.HasIndex("choiceId");

                    b.HasIndex("questionId");

                    b.ToTable("attempt_answer", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.Property<Guid>("choiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("choiceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uuid");

                    b.HasKey("choiceId");

                    b.HasIndex("questionId");

                    b.ToTable("choice", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("conversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("conversationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("conversationId");

                    b.ToTable("conversation", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("courseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("thumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("courseId");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.CourseInstructor", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeftOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CourseId", "InstructorId", "AssignedOn");

                    b.HasIndex("InstructorId");

                    b.ToTable("course_instructor", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.Property<int>("balance_after")
                        .HasColumnType("integer");

                    b.Property<int>("balance_before")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("transaction_id");

                    b.HasIndex("user_id");

                    b.ToTable("credit_transactions", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("documentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("documentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("lessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("documentId");

                    b.HasIndex("lessonId");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("enrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("enrollDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("enrollmentId");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("feedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<string>("reply")
                        .HasColumnType("text");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("feedbackId");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.InstructorProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.Property<string>("experience")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("introduction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("teachingStyle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("userId");

                    b.ToTable("instructor_profile", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("lessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<int>("lessonOrder")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("lessonId");

                    b.HasIndex("courseId");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("progressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("isCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("lessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("progressId");

                    b.HasIndex("lessonId");

                    b.HasIndex("userId");

                    b.ToTable("lesson_progress", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Livestream", b =>
                {
                    b.Property<Guid>("livestreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("lessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("livestreamId");

                    b.HasIndex("lessonId")
                        .IsUnique();

                    b.ToTable("livestream", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("conversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("senderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("messageId");

                    b.HasIndex("conversationId");

                    b.HasIndex("senderId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("transactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("paymentId");

                    b.HasIndex("userId");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("questionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("questionId");

                    b.HasIndex("SubContentId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.QuestionAttachment", b =>
                {
                    b.Property<Guid>("attachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("mediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mediaUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uuid");

                    b.HasKey("attachmentId");

                    b.HasIndex("questionId");

                    b.ToTable("question_attachment", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("reportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reportContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("reportedInstructorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("reporterStudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("reportId");

                    b.HasIndex("reportedInstructorId");

                    b.HasIndex("reporterStudentId");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("roleId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            roleId = new Guid("8dd36044-84d4-4e4b-8162-34b7a421657c"),
                            description = "Student role",
                            roleName = "STUDENT"
                        },
                        new
                        {
                            roleId = new Guid("8174528c-7f5b-4277-aa1a-1150e7b8b275"),
                            description = "Instructor role",
                            roleName = "INSTRUCTOR"
                        },
                        new
                        {
                            roleId = new Guid("0d1c9d64-3be8-4d5c-9ad0-062f83a3a7f8"),
                            description = "Academic Manager role",
                            roleName = "ACADEMIC_MANAGER"
                        },
                        new
                        {
                            roleId = new Guid("d500140c-99c5-452f-b44c-a3b4e650d0e6"),
                            description = "Administrator role",
                            roleName = "ADMIN"
                        });
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.Property<string>("currentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("learningGoals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.ToTable("student_profile", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("planId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("createdByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("studentId")
                        .HasColumnType("uuid");

                    b.HasKey("planId");

                    b.HasIndex("createdByStaffId");

                    b.HasIndex("studentId");

                    b.ToTable("study_plan", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlanItem", b =>
                {
                    b.Property<Guid>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courseId")
                        .HasColumnType("uuid");

                    b.Property<string>("itemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("planId")
                        .HasColumnType("uuid");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("testId")
                        .HasColumnType("uuid");

                    b.HasKey("itemId");

                    b.HasIndex("courseId");

                    b.HasIndex("planId");

                    b.HasIndex("testId");

                    b.ToTable("study_plan_item", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.SubContent", b =>
                {
                    b.Property<Guid>("SubContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SubContentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SubContentId");

                    b.ToTable("sub_contents", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("testId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestTemplateTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("availableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("availableTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("durationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("lessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("maxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("testType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("testId");

                    b.HasIndex("TestTemplateTypeId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("lessonId");

                    b.ToTable("test", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.Property<Guid>("attemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("attemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("isPass")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("testId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("attemptId");

                    b.HasIndex("testId");

                    b.HasIndex("userId");

                    b.ToTable("test_attempt", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestQuestion", b =>
                {
                    b.Property<Guid>("testQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("testId")
                        .HasColumnType("uuid");

                    b.HasKey("testQuestionId");

                    b.HasIndex("questionId");

                    b.HasIndex("testId");

                    b.ToTable("test_question", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestScoreSummary", b =>
                {
                    b.Property<Guid>("TestScoreSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<int>("grammar_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("grammar_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("kanji_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("kanji_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("listening_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("listening_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("passing_percentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("percentage_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("reading_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("reading_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("total_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("total_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("vocab_max_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("vocab_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("TestScoreSummaryId");

                    b.HasIndex("TestAttemptId");

                    b.HasIndex("TestId");

                    b.ToTable("test_score_summary", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplate", b =>
                {
                    b.Property<Guid>("templateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestTemplateTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("durationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("templateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("toPassPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("totalScore")
                        .HasColumnType("integer");

                    b.HasKey("templateId");

                    b.HasIndex("TestTemplateTypeId");

                    b.ToTable("test_template", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplateConfig", b =>
                {
                    b.Property<Guid>("configId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("pointPerQuestion")
                        .HasColumnType("integer");

                    b.Property<int>("questionCount")
                        .HasColumnType("integer");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("subContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("templateId")
                        .HasColumnType("uuid");

                    b.Property<int>("totalPoints")
                        .HasColumnType("integer");

                    b.HasKey("configId");

                    b.HasIndex("subContentId");

                    b.HasIndex("templateId");

                    b.ToTable("test_template_config", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplateType", b =>
                {
                    b.Property<Guid>("TestTemplateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("courseLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("testType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("TestTemplateTypeId");

                    b.HasIndex("userId");

                    b.ToTable("test_template_type", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("avatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("credit")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationsconversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("attemptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Choice", "Choice")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("choiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("Question");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.CourseInstructor", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Document", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Documents")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.InstructorProfile", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("JCertPreApplication.Domain.Entities.InstructorProfile", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Livestream", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithOne("Livestream")
                        .HasForeignKey("JCertPreApplication.Domain.Entities.Livestream", "lessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Message", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("conversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Payment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Question", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.SubContent", "SubContent")
                        .WithMany("Questions")
                        .HasForeignKey("SubContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubContent");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.QuestionAttachment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("QuestionAttachments")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Report", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "InstructorUser")
                        .WithMany("InstructorReports")
                        .HasForeignKey("reportedInstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "StudentUser")
                        .WithMany("StudentReports")
                        .HasForeignKey("reporterStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstructorUser");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("JCertPreApplication.Domain.Entities.StudentProfile", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "Staff")
                        .WithMany("StaffCreatePlans")
                        .HasForeignKey("createdByStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "Student")
                        .WithMany("StudentPlans")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlanItem", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JCertPreApplication.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("planId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Test", "Test")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("testId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Course");

                    b.Navigation("StudyPlan");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.TestTemplateType", "TestTemplateType")
                        .WithMany("Tests")
                        .HasForeignKey("TestTemplateTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTests")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Tests")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lesson");

                    b.Navigation("TestTemplateType");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Test", "Test")
                        .WithMany("TestAttempts")
                        .HasForeignKey("testId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestQuestion", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("TestQuestions")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("testId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestScoreSummary", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("TestScoreSummaries")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JCertPreApplication.Domain.Entities.Test", "Test")
                        .WithMany("TestScoreSummaries")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplate", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.TestTemplateType", "TestTemplateType")
                        .WithMany("TestTemplates")
                        .HasForeignKey("TestTemplateTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("TestTemplateType");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplateConfig", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.SubContent", "SubContent")
                        .WithMany("TestTemplateConfigs")
                        .HasForeignKey("subContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.TestTemplate", "TestTemplate")
                        .WithMany("TestTemplateConfigs")
                        .HasForeignKey("templateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubContent");

                    b.Navigation("TestTemplate");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplateType", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "CreatedByUser")
                        .WithMany("TestTemplateTypes")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.User", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseInstructors");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Lessons");

                    b.Navigation("StudyPlanItems");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Livestream");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Question", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("Choices");

                    b.Navigation("QuestionAttachments");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("StudyPlanItems");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.SubContent", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestTemplateConfigs");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.Navigation("StudyPlanItems");

                    b.Navigation("TestAttempts");

                    b.Navigation("TestQuestions");

                    b.Navigation("TestScoreSummaries");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("TestScoreSummaries");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplate", b =>
                {
                    b.Navigation("TestTemplateConfigs");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestTemplateType", b =>
                {
                    b.Navigation("TestTemplates");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedTests");

                    b.Navigation("CreditTransactions");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("InstructorCourses");

                    b.Navigation("InstructorProfile")
                        .IsRequired();

                    b.Navigation("InstructorReports");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Messages");

                    b.Navigation("Payments");

                    b.Navigation("StaffCreatePlans");

                    b.Navigation("StudentPlans");

                    b.Navigation("StudentProfile")
                        .IsRequired();

                    b.Navigation("StudentReports");

                    b.Navigation("TestAttempts");

                    b.Navigation("TestTemplateTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
