// <auto-generated />
using System;
using JCertPreApplication.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JCertPreApplication.Persistence.Migrations
{
    [DbContext(typeof(JCertPreDatabaseContext))]
    partial class JCertPreDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.Property<Guid>("ConversationsconversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantsuserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationsconversationId", "ParticipantsuserId");

                    b.HasIndex("ParticipantsuserId");

                    b.ToTable("ConversationParticipant", (string)null);
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("answerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("attemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("choiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("answerId");

                    b.HasIndex("attemptId");

                    b.HasIndex("choiceId");

                    b.HasIndex("questionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.Property<Guid>("choiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("choiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("choiceId");

                    b.HasIndex("questionId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("conversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("conversationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("conversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("courseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("staffCreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("courseId");

                    b.HasIndex("staffCreateUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("documentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("documentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("lessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("documentId");

                    b.HasIndex("lessonId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("enrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("enrollDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("enrollmentId");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("feedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("reply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("feedbackId");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.InstructorProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("experience")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("introduction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("teachingStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userId");

                    b.ToTable("InstructorProfiles");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("lessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("lessonOrder")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("lessonId");

                    b.HasIndex("courseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Livestream", b =>
                {
                    b.Property<Guid>("livestreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("meetingUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recordingUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("livestreamId");

                    b.HasIndex("courseId");

                    b.ToTable("Livestreams");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("conversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("senderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("messageId");

                    b.HasIndex("conversationId");

                    b.HasIndex("senderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("paymentId");

                    b.HasIndex("userId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("tagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("questionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.QuestionAttachment", b =>
                {
                    b.Property<Guid>("attachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mediaUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("questionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("attachmentId");

                    b.HasIndex("questionId");

                    b.ToTable("QuestionAttachments");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("reportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("reportContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("reportedInstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("reporterStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("reportId");

                    b.HasIndex("reportedInstructorId");

                    b.HasIndex("reporterStudentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("currentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("learningGoals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("planId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("createdByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("studentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("planId");

                    b.HasIndex("createdByStaffId");

                    b.HasIndex("studentId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlanItem", b =>
                {
                    b.Property<Guid>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("itemIdRef")
                        .HasColumnType("int");

                    b.Property<string>("itemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("planId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("sequence")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("itemId");

                    b.HasIndex("planId");

                    b.ToTable("StudyPlanItems");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("tagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contentDetail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("contentSection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tagLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("tagScore")
                        .HasColumnType("int");

                    b.HasKey("tagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("testId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("durationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("lessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("testType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("testId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("lessonId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.Property<Guid>("attemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isPass")
                        .HasColumnType("bit");

                    b.Property<int>("languageKnowledgeScore")
                        .HasColumnType("int");

                    b.Property<int>("listeningScore")
                        .HasColumnType("int");

                    b.Property<int>("readingScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("testId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("totalScore")
                        .HasColumnType("int");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("attemptId");

                    b.HasIndex("testId");

                    b.HasIndex("userId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("avatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("credit")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionsquestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionsquestionId", "tagId");

                    b.HasIndex("tagId");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("QuestionTest", b =>
                {
                    b.Property<Guid>("QuestionsquestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeststestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionsquestionId", "TeststestId");

                    b.HasIndex("TeststestId");

                    b.ToTable("QuestionTests", (string)null);
                });

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationsconversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.TestAttempt", "TestAttempt")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("attemptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Choice", "Choice")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("choiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("Question");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Course", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("staffCreateUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Document", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Documents")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.InstructorProfile", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("JCertPreApplication.Domain.Entities.InstructorProfile", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Livestream", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Course", "Course")
                        .WithMany("Livestreams")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Message", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("conversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Payment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.QuestionAttachment", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", "Question")
                        .WithMany("QuestionAttachments")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Report", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "InstructorUser")
                        .WithMany("InstructorReports")
                        .HasForeignKey("reportedInstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "StudentUser")
                        .WithMany("StudentReports")
                        .HasForeignKey("reporterStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstructorUser");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("JCertPreApplication.Domain.Entities.StudentProfile", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "Staff")
                        .WithMany("StaffCreatePlans")
                        .HasForeignKey("createdByStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "Student")
                        .WithMany("StudentPlans")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlanItem", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("planId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTests")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Tests")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Test", "Test")
                        .WithMany("TestAttempts")
                        .HasForeignKey("testId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsquestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionTest", b =>
                {
                    b.HasOne("JCertPreApplication.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsquestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JCertPreApplication.Domain.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TeststestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Choice", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Lessons");

                    b.Navigation("Livestreams");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Question", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("Choices");

                    b.Navigation("QuestionAttachments");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("StudyPlanItems");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.Test", b =>
                {
                    b.Navigation("TestAttempts");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.TestAttempt", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("JCertPreApplication.Domain.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("CreatedTests");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("InstructorProfile")
                        .IsRequired();

                    b.Navigation("InstructorReports");

                    b.Navigation("Messages");

                    b.Navigation("Payments");

                    b.Navigation("StaffCreatePlans");

                    b.Navigation("StudentPlans");

                    b.Navigation("StudentProfile")
                        .IsRequired();

                    b.Navigation("StudentReports");

                    b.Navigation("TestAttempts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
